# Generated by Django 5.0.6 on 2024-06-06 16:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('BannerID', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999)])),
                ('BannerIcon', models.URLField(max_length=250)),
                ('BannerName', models.CharField(max_length=250)),
                ('FeaturedCharacters', models.JSONField()),
                ('BannerDetails', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('CardID', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999)])),
                ('CardName', models.CharField(max_length=250)),
                ('CardIcon', models.URLField(max_length=250)),
                ('CardArt', models.URLField(max_length=250)),
                ('CardRarity', models.CharField(max_length=3)),
                ('CardClass', models.CharField(max_length=50)),
                ('CardType', models.CharField(max_length=3)),
                ('CardTypeIcon', models.URLField(max_length=250)),
                ('CardCost', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('CardLeaderOf', models.TextField()),
                ('CardLeader', models.TextField()),
                ('CardSAName', models.CharField(max_length=250)),
                ('CardSA', models.TextField()),
                ('CardPassiveName', models.CharField(max_length=250)),
                ('CardPassive', models.TextField()),
                ('CardReleaseJP', models.DateField()),
                ('CardReleaseGL', models.DateField()),
                ('CardCategories', models.TextField()),
                ('CardActiveName', models.CharField(max_length=250)),
                ('CardActive', models.TextField()),
                ('CardCond', models.TextField()),
                ('CardLinks', models.TextField()),
                ('ObtainedFrom', models.URLField()),
                ('BaseHP', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999)])),
                ('BaseATK', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999)])),
                ('BaseDEF', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999)])),
                ('MaxLevelHP', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999)])),
                ('MaxLevelATK', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999)])),
                ('MaxLevelDEF', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999)])),
                ('HP55', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999)])),
                ('ATK55', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999)])),
                ('DEF55', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999)])),
                ('HP100', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999)])),
                ('ATK100', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999)])),
                ('DEF100', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999)])),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('EventId', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999)])),
                ('EventIcon', models.URLField(max_length=250)),
                ('EventName', models.CharField(max_length=250)),
                ('EventType', models.CharField(max_length=250)),
                ('EventWeakness', models.CharField(max_length=250)),
                ('EventReleaseJP', models.DateField()),
                ('EventReleaseGL', models.DateField()),
                ('EventDetails', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('EventTypeId', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999)])),
                ('EventTypeName', models.CharField(max_length=250)),
                ('EventTypeContent', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('NewsId', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999)])),
                ('NewsImage', models.URLField(max_length=250)),
                ('NewsImage2', models.URLField(max_length=250)),
                ('NewsName', models.CharField(max_length=250)),
                ('NewsBody', models.TextField()),
            ],
        ),
    ]
