# Generated by Django 5.0.6 on 2024-06-06 18:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DokkanDB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('CategoryID', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999)])),
                ('CategoryIcon', models.URLField(max_length=250)),
                ('CategoryName', models.CharField(max_length=250)),
                ('CategoryCharacters', models.JSONField()),
            ],
        ),
    ]
